#ifndef MY_STRACE_H
#define MY_STRACE_H

#include <stdio.h>
#include <sys/ptrace.h>
#include <sys/reg.h>
#include <sys/syscall.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <unistd.h>

#include "utils.h"

char *syscall_names[] = { "read",
                          "write",
                          "open",
                          "close",
                          "stat",
                          "fstat",
                          "lstat",
                          "poll",
                          "lseek",
                          "mmap",
                          "mprotect",
                          "munmap",
                          "brk",
                          "rt_sigaction",
                          "rt_sigprocmask",
                          "rt_sigreturn",
                          "ioctl",
                          "pread64",
                          "pwrite64",
                          "readv",
                          "writev",
                          "access",
                          "pipe",
                          "select",
                          "sched_yield",
                          "mremap",
                          "msync",
                          "mincore",
                          "madvise",
                          "shmget",
                          "shmat",
                          "shmctl",
                          "dup",
                          "dup2",
                          "pause",
                          "nanosleep",
                          "getitimer",
                          "alarm",
                          "setitimer",
                          "getpid",
                          "sendfile",
                          "socket",
                          "connect",
                          "accept",
                          "sendto",
                          "recvfrom",
                          "sendmsg",
                          "recvmsg",
                          "shutdown",
                          "bind",
                          "listen",
                          "getsockname",
                          "getpeername",
                          "socketpair",
                          "setsockopt",
                          "getsockopt",
                          "clone",
                          "fork",
                          "vfork",
                          "execve",
                          "exit",
                          "wait4",
                          "kill",
                          "uname",
                          "semget",
                          "semop",
                          "semctl",
                          "shmdt",
                          "msgget",
                          "msgsnd",
                          "msgrcv",
                          "msgctl",
                          "fcntl",
                          "flock",
                          "fsync",
                          "fdatasync",
                          "truncate",
                          "ftruncate",
                          "getdents",
                          "getcwd",
                          "chdir",
                          "fchdir",
                          "rename",
                          "mkdir",
                          "rmdir",
                          "creat",
                          "link",
                          "unlink",
                          "symlink",
                          "readlink",
                          "chmod",
                          "fchmod",
                          "chown",
                          "fchown",
                          "lchown",
                          "umask",
                          "gettimeofday",
                          "getrlimit",
                          "getrusage",
                          "sysinfo",
                          "times",
                          "ptrace",
                          "getuid",
                          "syslog",
                          "getgid",
                          "setuid",
                          "setgid",
                          "geteuid",
                          "getegid",
                          "setpgid",
                          "getppid",
                          "getpgrp",
                          "setsid",
                          "setreuid",
                          "setregid",
                          "getgroups",
                          "setgroups",
                          "setresuid",
                          "getresuid",
                          "setresgid",
                          "getresgid",
                          "getpgid",
                          "setfsuid",
                          "setfsgid",
                          "getsid",
                          "capget",
                          "capset",
                          "rt_sigpending",
                          "rt_sigtimedwait",
                          "rt_sigqueueinfo",
                          "rt_sigsuspend",
                          "sigaltstack",
                          "utime",
                          "mknod",
                          "uselib",
                          "personality",
                          "ustat",
                          "statfs",
                          "fstatfs",
                          "sysfs",
                          "getpriority",
                          "setpriority",
                          "sched_setparam",
                          "sched_getparam",
                          "sched_setscheduler",
                          "sched_getscheduler",
                          "sched_get_priority_max",
                          "sched_get_priority_min",
                          "sched_rr_get_interval",
                          "mlock",
                          "munlock",
                          "mlockall",
                          "munlockall",
                          "vhangup",
                          "modify_ldt",
                          "pivot_root",
                          "sysctl",
                          "prctl",
                          "arch_prctl",
                          "adjtimex",
                          "setrlimit",
                          "chroot",
                          "sync",
                          "acct",
                          "settimeofday",
                          "mount",
                          "umount2",
                          "swapon",
                          "swapoff",
                          "reboot",
                          "sethostname",
                          "setdomainname",
                          "iopl",
                          "ioperm",
                          "create_module",
                          "init_module",
                          "delete_module",
                          "get_kernel_syms",
                          "query_module",
                          "quotactl",
                          "nfsservctl",
                          "getpmsg",
                          "putpmsg",
                          "afs_syscall",
                          "tuxcall",
                          "security",
                          "gettid",
                          "readahead",
                          "setxattr",
                          "lsetxattr",
                          "fsetxattr",
                          "getxattr",
                          "lgetxattr",
                          "fgetxattr",
                          "listxattr",
                          "llistxattr",
                          "flistxattr",
                          "removexattr",
                          "lremovexattr",
                          "fremovexattr",
                          "tkill",
                          "time",
                          "futex",
                          "sched_setaffinity",
                          "sched_getaffinity",
                          "set_thread_area",
                          "io_setup",
                          "io_destroy",
                          "io_getevents",
                          "io_submit",
                          "io_cancel",
                          "get_thread_area",
                          "lookup_dcookie",
                          "epoll_create",
                          "epoll_ctl_old",
                          "epoll_wait_old",
                          "remap_file_pages",
                          "getdents64",
                          "set_tid_address",
                          "restart_syscall",
                          "semtimedop",
                          "fadvise64",
                          "timer_create",
                          "timer_settime",
                          "timer_gettime",
                          "timer_getoverrun",
                          "timer_delete",
                          "clock_settime",
                          "clock_gettime",
                          "clock_getres",
                          "clock_nanosleep",
                          "exit_group",
                          "epoll_wait",
                          "epoll_ctl",
                          "tgkill",
                          "utimes",
                          "vserver",
                          "mbind",
                          "set_mempolicy",
                          "get_mempolicy",
                          "mq_open",
                          "mq_unlink",
                          "mq_timedsend",
                          "mq_timedreceive",
                          "mq_notify",
                          "mq_getsetattr",
                          "kexec_load",
                          "waitid",
                          "add_key",
                          "request_key",
                          "keyctl",
                          "ioprio_set",
                          "ioprio_get",
                          "inotify_init",
                          "inotify_add_watch",
                          "inotify_rm_watch",
                          "migrate_pages",
                          "openat",
                          "mkdirat",
                          "mknodat",
                          "fchownat",
                          "futimesat",
                          "newfstatat",
                          "unlinkat",
                          "renameat",
                          "linkat",
                          "symlinkat",
                          "readlinkat",
                          "fchmodat",
                          "faccessat",
                          "pselect6",
                          "ppoll",
                          "unshare",
                          "set_robust_list",
                          "get_robust_list",
                          "splice",
                          "tee",
                          "sync_file_range",
                          "vmsplice",
                          "move_pages",
                          "utimensat",
                          "epoll_pwait",
                          "signalfd",
                          "timerfd_create",
                          "eventfd",
                          "fallocate",
                          "timerfd_settime",
                          "timerfd_gettime",
                          "accept4",
                          "signalfd4",
                          "eventfd2",
                          "epoll_create1",
                          "dup3",
                          "pipe2",
                          "inotify_init1",
                          "preadv",
                          "pwritev",
                          "rt_tgsigqueueinfo",
                          "perf_event_open",
                          "recvmmsg",
                          "fanotify_init",
                          "fanotify_mark",
                          "prlimit64",
                          "name_to_handle_at",
                          "open_by_handle_at",
                          "clock_adjtime",
                          "syncfs",
                          "sendmmsg",
                          "setns",
                          "getcpu",
                          "process_vm_readv",
                          "process_vm_writev",
                          "kcmp",
                          "finit_module",
                          "sched_setattr",
                          "sched_getattr",
                          "renameat2",
                          "seccomp",
                          "getrandom",
                          "memfd_create",
                          "kexec_file_load",
                          "bpf",
                          "execveat",
                          "userfaultfd",
                          "membarrier",
                          "mlock2",
                          "copy_file_range",
                          "preadv2",
                          "pwritev2",
                          "pkey_mprotect",
                          "pkey_alloc",
                          "pkey_free",
                          "statx",
                          "io_pgetevents",
                          "rseq",
                          "Unknown syscall" };

typedef struct
{
    char *name;
    void (*print_fonction)(info data);
} Arg;

typedef struct
{
    char *name;
    int nbArg;
    Arg args[6];
} SysCall;

SysCall sysArgList[] = {
    { "read",
      3,
      { { "fd", print_int }, { "buf", print_ptr }, { "count", print_int } } },
    { "write",
      3,
      { { "fd", print_int }, { "buf", print_ptr }, { "count", print_int } } },
    { "open", 2, { { "pathname", print_str }, { "flags", print_int } } },
    { "close", 1, { { "fd", print_int } } },
    { "stat", 2, { { "pathname", print_str }, { "statbuf", print_ptr } } },
    { "fstat", 2, { { "fd", print_int }, { "statbuf", print_ptr } } },
    { "lstat", 2, { { "pathname", print_str }, { "statbuf", print_ptr } } },
    { "poll",
      3,
      { { "fds", print_ptr },
        { "nfds", print_int },
        { "timeout", print_int } } },
    { "lseek",
      3,
      { { "fd", print_int },
        { "offset", print_long },
        { "whence", print_int } } },
    { "mmap",
      6,
      { { "addr", print_ptr },
        { "length", print_long },
        { "prot", print_int },
        { "flags", print_int },
        { "fd", print_int },
        { "offset", print_long } } },
    { "mprotect",
      3,
      { { "addr", print_ptr }, { "len", print_long }, { "prot", print_int } } },
    { "munmap", 2, { { "addr", print_ptr }, { "length", print_long } } },
    { "brk", 1, { { "addr", print_ptr } } },
    { "rt_sigaction",
      4,
      { { "signum", print_int },
        { "act", print_ptr },
        { "oldact", print_ptr },
        { "sigsetsize", print_int } } },
    { "rt_sigprocmask",
      4,
      { { "how", print_int },
        { "set", print_ptr },
        { "oldset", print_ptr },
        { "sigsetsize", print_int } } },
    { "rt_sigreturn", 0, { { "null", NULL } } },
    { "ioctl",
      3,
      { { "fd", print_int },
        { "request", print_hexa },
        { "arg", print_ptr } } },
    { "pread64",
      4,
      { { "fd", print_int },
        { "buf", print_ptr },
        { "count", print_int },
        { "offset", print_long } } },
    { "pwrite64",
      4,
      { { "fd", print_int },
        { "buf", print_ptr },
        { "count", print_int },
        { "offset", print_long } } },
    { "readv",
      3,
      { { "fd", print_int }, { "iov", print_ptr }, { "iovcnt", print_int } } },
    { "writev",
      3,
      { { "fd", print_int }, { "iov", print_ptr }, { "iovcnt", print_int } } },
    { "access", 2, { { "pathname", print_str }, { "mode", print_int } } },
    { "pipe", 1, { { "pipefd", print_ptr } } },
    { "select",
      5,
      { { "nfds", print_int },
        { "readfds", print_ptr },
        { "writefds", print_ptr },
        { "exceptfds", print_ptr },
        { "timeout", print_ptr } } },
    { "sched_yield", 0, { { "null", NULL } } },
    { "mremap",
      5,
      { { "old_address", print_ptr },
        { "old_size", print_long },
        { "new_size", print_long },
        { "flags", print_int },
        { "new_address", print_ptr } } },
    { "msync",
      3,
      { { "addr", print_ptr },
        { "length", print_long },
        { "flags", print_int } } },
    { "mincore",
      3,
      { { "addr", print_ptr },
        { "length", print_long },
        { "vec", print_ptr } } },
    { "madvise",
      3,
      { { "addr", print_ptr },
        { "length", print_long },
        { "advice", print_int } } },
    { "shmget",
      3,
      { { "key", print_int },
        { "size", print_long },
        { "shmflg", print_int } } },
    { "shmat",
      3,
      { { "shmid", print_int },
        { "shmaddr", print_ptr },
        { "shmflg", print_int } } },
    { "shmctl",
      3,
      { { "shmid", print_int }, { "cmd", print_int }, { "buf", print_ptr } } },
    { "dup", 1, { { "oldfd", print_int } } },
    { "dup2", 2, { { "oldfd", print_int }, { "newfd", print_int } } },
    { "pause", 0, { { "null", NULL } } },
    { "nanosleep", 2, { { "req", print_ptr }, { "rem", print_ptr } } },
    { "getitimer", 2, { { "which", print_int }, { "curr_value", print_ptr } } },
    { "alarm", 1, { { "seconds", print_int } } },
    { "setitimer",
      3,
      { { "which", print_int },
        { "new_value", print_ptr },
        { "old_value", print_ptr } } },
    { "getpid", 0, { { "null", NULL } } },
    { "sendfile",
      4,
      { { "out_fd", print_int },
        { "in_fd", print_int },
        { "offset", print_ptr },
        { "count", print_long } } },
    { "socket",
      3,
      { { "domain", print_int },
        { "type", print_int },
        { "protocol", print_int } } },
    { "connect",
      3,
      { { "sockfd", print_int },
        { "addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "accept",
      3,
      { { "sockfd", print_int },
        { "addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "sendto",
      6,
      { { "sockfd", print_int },
        { "buf", print_ptr },
        { "len", print_long },
        { "flags", print_int },
        { "dest_addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "recvfrom",
      6,
      { { "sockfd", print_int },
        { "buf", print_ptr },
        { "len", print_long },
        { "flags", print_int },
        { "src_addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "sendmsg",
      3,
      { { "sockfd", print_int },
        { "msg", print_ptr },
        { "flags", print_int } } },
    { "recvmsg",
      3,
      { { "sockfd", print_int },
        { "msg", print_ptr },
        { "flags", print_int } } },
    { "shutdown", 2, { { "sockfd", print_int }, { "how", print_int } } },
    { "bind",
      3,
      { { "sockfd", print_int },
        { "addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "listen", 2, { { "sockfd", print_int }, { "backlog", print_int } } },
    { "getsockname",
      3,
      { { "sockfd", print_int },
        { "addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "getpeername",
      3,
      { { "sockfd", print_int },
        { "addr", print_ptr },
        { "addrlen", print_ptr } } },
    { "socketpair",
      4,
      { { "domain", print_int },
        { "type", print_int },
        { "protocol", print_int },
        { "sv", print_ptr } } },
    { "setsockopt",
      5,
      { { "sockfd", print_int },
        { "level", print_int },
        { "optname", print_int },
        { "optval", print_ptr },
        { "optlen", print_ptr } } },
    { "getsockopt",
      5,
      { { "sockfd", print_int },
        { "level", print_int },
        { "optname", print_int },
        { "optval", print_ptr },
        { "optlen", print_ptr } } },
    { "clone",
      5,
      { { "flags", print_long },
        { "child_stack", print_ptr },
        { "ptid", print_ptr },
        { "ctid", print_ptr },
        { "tls", print_ptr } } },
    { "fork", 0, { { "null", NULL } } },
    { "vfork", 0, { { "null", NULL } } },
    { "execve",
      3,
      { { "pathname", print_str },
        { "argv", print_ptr },
        { "envp", print_ptr } } },
    { "exit", 1, { { "status", print_int } } },
    { "wait4",
      4,
      { { "pid", print_int },
        { "wstatus", print_ptr },
        { "options", print_int },
        { "rusage", print_ptr } } },
    { "kill", 2, { { "pid", print_int }, { "sig", print_int } } },
    { "uname", 1, { { "buf", print_ptr } } },
    { "semget",
      3,
      { { "key", print_int },
        { "nsems", print_int },
        { "semflg", print_int } } },
    { "semop",
      3,
      { { "semid", print_int },
        { "sops", print_ptr },
        { "nsops", print_int } } },
    { "semctl",
      4,
      { { "semid", print_int },
        { "semnum", print_int },
        { "cmd", print_int },
        { "arg", print_ptr } } },
    { "shmdt", 1, { { "shmaddr", print_ptr } } },
    { "msgget", 2, { { "key", print_int }, { "msgflg", print_int } } },
    { "msgsnd",
      4,
      { { "msqid", print_int },
        { "msgp", print_ptr },
        { "msgsz", print_long },
        { "msgflg", print_int } } },
    { "msgrcv",
      5,
      { { "msqid", print_int },
        { "msgp", print_ptr },
        { "msgsz", print_long },
        { "msgtyp", print_long },
        { "msgflg", print_int } } },
    { "msgctl",
      3,
      { { "msqid", print_int }, { "cmd", print_int }, { "buf", print_ptr } } },
    { "fcntl",
      3,
      { { "fd", print_int }, { "cmd", print_int }, { "arg", print_ptr } } },
    { "flock", 2, { { "fd", print_int }, { "operation", print_int } } },
    { "fsync", 1, { { "fd", print_int } } },
    { "fdatasync", 1, { { "fd", print_int } } },
    { "truncate", 2, { { "pathname", print_str }, { "length", print_long } } },
    { "ftruncate", 2, { { "fd", print_int }, { "length", print_long } } },
    { "getdents",
      3,
      { { "fd", print_int }, { "dirp", print_ptr }, { "count", print_int } } },
    { "getcwd", 2, { { "buf", print_ptr }, { "size", print_long } } },
    { "chdir", 1, { { "path", print_str } } },
    { "fchdir", 1, { { "fd", print_int } } },
    { "rename", 2, { { "oldpath", print_str }, { "newpath", print_str } } },
    { "mkdir", 2, { { "pathname", print_str }, { "mode", print_int } } },
    { "rmdir", 1, { { "pathname", print_str } } },
    { "creat", 2, { { "pathname", print_str }, { "mode", print_int } } },
    { "link", 2, { { "oldpath", print_str }, { "newpath", print_str } } },
    { "unlink", 1, { { "pathname", print_str } } }
};

char *get_syscall_name(long syscall_number);

#endif /* !MY_STRACE_H */
