#ifndef MY_STRACE_H
#define MY_STRACE_H

#include <stdio.h>
#include <sys/ptrace.h>
#include <sys/reg.h>
#include <sys/syscall.h>
#include <sys/user.h>
#include <sys/wait.h>
#include <unistd.h>

char *syscall_names[] = {"read",
                         "write",
                         "open",
                         "close",
                         "stat",
                         "fstat",
                         "lstat",
                         "poll",
                         "lseek",
                         "mmap",
                         "mprotect",
                         "munmap",
                         "brk",
                         "rt_sigaction",
                         "rt_sigprocmask",
                         "rt_sigreturn",
                         "ioctl",
                         "pread64",
                         "pwrite64",
                         "readv",
                         "writev",
                         "access",
                         "pipe",
                         "select",
                         "sched_yield",
                         "mremap",
                         "msync",
                         "mincore",
                         "madvise",
                         "shmget",
                         "shmat",
                         "shmctl",
                         "dup",
                         "dup2",
                         "pause",
                         "nanosleep",
                         "getitimer",
                         "alarm",
                         "setitimer",
                         "getpid",
                         "sendfile",
                         "socket",
                         "connect",
                         "accept",
                         "sendto",
                         "recvfrom",
                         "sendmsg",
                         "recvmsg",
                         "shutdown",
                         "bind",
                         "listen",
                         "getsockname",
                         "getpeername",
                         "socketpair",
                         "setsockopt",
                         "getsockopt",
                         "clone",
                         "fork",
                         "vfork",
                         "execve",
                         "exit",
                         "wait4",
                         "kill",
                         "uname",
                         "semget",
                         "semop",
                         "semctl",
                         "shmdt",
                         "msgget",
                         "msgsnd",
                         "msgrcv",
                         "msgctl",
                         "fcntl",
                         "flock",
                         "fsync",
                         "fdatasync",
                         "truncate",
                         "ftruncate",
                         "getdents",
                         "getcwd",
                         "chdir",
                         "fchdir",
                         "rename",
                         "mkdir",
                         "rmdir",
                         "creat",
                         "link",
                         "unlink",
                         "symlink",
                         "readlink",
                         "chmod",
                         "fchmod",
                         "chown",
                         "fchown",
                         "lchown",
                         "umask",
                         "gettimeofday",
                         "getrlimit",
                         "getrusage",
                         "sysinfo",
                         "times",
                         "ptrace",
                         "getuid",
                         "syslog",
                         "getgid",
                         "setuid",
                         "setgid",
                         "geteuid",
                         "getegid",
                         "setpgid",
                         "getppid",
                         "getpgrp",
                         "setsid",
                         "setreuid",
                         "setregid",
                         "getgroups",
                         "setgroups",
                         "setresuid",
                         "getresuid",
                         "setresgid",
                         "getresgid",
                         "getpgid",
                         "setfsuid",
                         "setfsgid",
                         "getsid",
                         "capget",
                         "capset",
                         "rt_sigpending",
                         "rt_sigtimedwait",
                         "rt_sigqueueinfo",
                         "rt_sigsuspend",
                         "sigaltstack",
                         "utime",
                         "mknod",
                         "uselib",
                         "personality",
                         "ustat",
                         "statfs",
                         "fstatfs",
                         "sysfs",
                         "getpriority",
                         "setpriority",
                         "sched_setparam",
                         "sched_getparam",
                         "sched_setscheduler",
                         "sched_getscheduler",
                         "sched_get_priority_max",
                         "sched_get_priority_min",
                         "sched_rr_get_interval",
                         "mlock",
                         "munlock",
                         "mlockall",
                         "munlockall",
                         "vhangup",
                         "modify_ldt",
                         "pivot_root",
                         "sysctl",
                         "prctl",
                         "arch_prctl",
                         "adjtimex",
                         "setrlimit",
                         "chroot",
                         "sync",
                         "acct",
                         "settimeofday",
                         "mount",
                         "umount2",
                         "swapon",
                         "swapoff",
                         "reboot",
                         "sethostname",
                         "setdomainname",
                         "iopl",
                         "ioperm",
                         "create_module",
                         "init_module",
                         "delete_module",
                         "get_kernel_syms",
                         "query_module",
                         "quotactl",
                         "nfsservctl",
                         "getpmsg",
                         "putpmsg",
                         "afs_syscall",
                         "tuxcall",
                         "security",
                         "gettid",
                         "readahead",
                         "setxattr",
                         "lsetxattr",
                         "fsetxattr",
                         "getxattr",
                         "lgetxattr",
                         "fgetxattr",
                         "listxattr",
                         "llistxattr",
                         "flistxattr",
                         "removexattr",
                         "lremovexattr",
                         "fremovexattr",
                         "tkill",
                         "time",
                         "futex",
                         "sched_setaffinity",
                         "sched_getaffinity",
                         "set_thread_area",
                         "io_setup",
                         "io_destroy",
                         "io_getevents",
                         "io_submit",
                         "io_cancel",
                         "get_thread_area",
                         "lookup_dcookie",
                         "epoll_create",
                         "epoll_ctl_old",
                         "epoll_wait_old",
                         "remap_file_pages",
                         "getdents64",
                         "set_tid_address",
                         "restart_syscall",
                         "semtimedop",
                         "fadvise64",
                         "timer_create",
                         "timer_settime",
                         "timer_gettime",
                         "timer_getoverrun",
                         "timer_delete",
                         "clock_settime",
                         "clock_gettime",
                         "clock_getres",
                         "clock_nanosleep",
                         "exit_group",
                         "epoll_wait",
                         "epoll_ctl",
                         "tgkill",
                         "utimes",
                         "vserver",
                         "mbind",
                         "set_mempolicy",
                         "get_mempolicy",
                         "mq_open",
                         "mq_unlink",
                         "mq_timedsend",
                         "mq_timedreceive",
                         "mq_notify",
                         "mq_getsetattr",
                         "kexec_load",
                         "waitid",
                         "add_key",
                         "request_key",
                         "keyctl",
                         "ioprio_set",
                         "ioprio_get",
                         "inotify_init",
                         "inotify_add_watch",
                         "inotify_rm_watch",
                         "migrate_pages",
                         "openat",
                         "mkdirat",
                         "mknodat",
                         "fchownat",
                         "futimesat",
                         "newfstatat",
                         "unlinkat",
                         "renameat",
                         "linkat",
                         "symlinkat",
                         "readlinkat",
                         "fchmodat",
                         "faccessat",
                         "pselect6",
                         "ppoll",
                         "unshare",
                         "set_robust_list",
                         "get_robust_list",
                         "splice",
                         "tee",
                         "sync_file_range",
                         "vmsplice",
                         "move_pages",
                         "utimensat",
                         "epoll_pwait",
                         "signalfd",
                         "timerfd_create",
                         "eventfd",
                         "fallocate",
                         "timerfd_settime",
                         "timerfd_gettime",
                         "accept4",
                         "signalfd4",
                         "eventfd2",
                         "epoll_create1",
                         "dup3",
                         "pipe2",
                         "inotify_init1",
                         "preadv",
                         "pwritev",
                         "rt_tgsigqueueinfo",
                         "perf_event_open",
                         "recvmmsg",
                         "fanotify_init",
                         "fanotify_mark",
                         "prlimit64",
                         "name_to_handle_at",
                         "open_by_handle_at",
                         "clock_adjtime",
                         "syncfs",
                         "sendmmsg",
                         "setns",
                         "getcpu",
                         "process_vm_readv",
                         "process_vm_writev",
                         "kcmp",
                         "finit_module",
                         "sched_setattr",
                         "sched_getattr",
                         "renameat2",
                         "seccomp",
                         "getrandom",
                         "memfd_create",
                         "kexec_file_load",
                         "bpf",
                         "execveat",
                         "userfaultfd",
                         "membarrier",
                         "mlock2",
                         "copy_file_range",
                         "preadv2",
                         "pwritev2",
                         "pkey_mprotect",
                         "pkey_alloc",
                         "pkey_free",
                         "statx",
                         "io_pgetevents",
                         "rseq",
                         "Unknown syscall"};

typedef struct {
  char *name;
} Arg;

typedef struct {
  char *name;
  int nbArg;
  Arg args[6];
} SysCall;

SysCall sysArgList[] = {
    {"read", 3, {{"fd"}, {"buf"}, {"count"}}},
    {"write", 3, {{"fd"}, {"buf"}, {"count"}}},
    {"open", 2, {{"pathname"}, {"flags"}}},
    {"close", 1, {{"fd"}}},
    {"stat", 2, {{"pathname"}, {"statbuf"}}},
    {"fstat", 2, {{"fd"}, {"statbuf"}}},
    {"lstat", 2, {{"pathname"}, {"statbuf"}}},
    {"poll", 3, {{"fds"}, {"nfds"}, {"timeout"}}},
    {"lseek", 3, {{"fd"}, {"offset"}, {"whence"}}},
    {"mmap",
     6,
     {{"addr"}, {"length"}, {"prot"}, {"flags"}, {"fd"}, {"offset"}}},
    {"mprotect", 3, {{"addr"}, {"len"}, {"prot"}}},
    {"munmap", 2, {{"addr"}, {"length"}}},
    {"brk", 1, {{"addr"}}},
    {"rt_sigaction", 4, {{"signum"}, {"act"}, {"oldact"}, {"sigsetsize"}}},
    {"rt_sigprocmask", 4, {{"how"}, {"set"}, {"oldset"}, {"sigsetsize"}}},
    {"rt_sigreturn", 0, {{"null"}}},
    {"ioctl", 3, {{"fd"}, {"request"}, {"arg"}}},
    {"pread64", 4, {{"fd"}, {"buf"}, {"count"}, {"offset"}}},
    {"pwrite64", 4, {{"fd"}, {"buf"}, {"count"}, {"offset"}}},
    {"readv", 3, {{"fd"}, {"iov"}, {"iovcnt"}}},
    {"writev", 3, {{"fd"}, {"iov"}, {"iovcnt"}}},
    {"access", 2, {{"pathname"}, {"mode"}}},
    {"pipe", 1, {{"pipefd"}}},
    {"select",
     5,
     {{"nfds"}, {"readfds"}, {"writefds"}, {"exceptfds"}, {"timeout"}}},
    {"sched_yield", 0, {{"null"}}},
    {"mremap",
     5,
     {{"old_address"}, {"old_size"}, {"new_size"}, {"flags"}, {"new_address"}}},
    {"msync", 3, {{"addr"}, {"length"}, {"flags"}}},
    {"mincore", 3, {{"addr"}, {"length"}, {"vec"}}},
    {"madvise", 3, {{"addr"}, {"length"}, {"advice"}}},
    {"shmget", 3, {{"key"}, {"size"}, {"shmflg"}}},
    {"shmat", 3, {{"shmid"}, {"shmaddr"}, {"shmflg"}}},
    {"shmctl", 3, {{"shmid"}, {"cmd"}, {"buf"}}},
    {"dup", 1, {{"oldfd"}}},
    {"dup2", 2, {{"oldfd"}, {"newfd"}}},
    {"pause", 0, {{"null"}}},
    {"nanosleep", 2, {{"req"}, {"rem"}}},
    {"getitimer", 2, {{"which"}, {"curr_value"}}},
    {"alarm", 1, {{"seconds"}}},
    {"setitimer", 3, {{"which"}, {"new_value"}, {"old_value"}}},
    {"getpid", 0, {{"null"}}},
    {"sendfile", 4, {{"out_fd"}, {"in_fd"}, {"offset"}, {"count"}}},
    {"socket", 3, {{"domain"}, {"type"}, {"protocol"}}},
    {"connect", 3, {{"sockfd"}, {"addr"}, {"addrlen"}}},
    {"accept", 3, {{"sockfd"}, {"addr"}, {"addrlen"}}},
    {"sendto",
     6,
     {{"sockfd"}, {"buf"}, {"len"}, {"flags"}, {"dest_addr"}, {"addrlen"}}},
    {"recvfrom",
     6,
     {{"sockfd"}, {"buf"}, {"len"}, {"flags"}, {"src_addr"}, {"addrlen"}}},
    {"sendmsg", 3, {{"sockfd"}, {"msg"}, {"flags"}}},
    {"recvmsg", 3, {{"sockfd"}, {"msg"}, {"flags"}}},
    {"shutdown", 2, {{"sockfd"}, {"how"}}},
    {"bind", 3, {{"sockfd"}, {"addr"}, {"addrlen"}}},
    {"listen", 2, {{"sockfd"}, {"backlog"}}},
    {"getsockname", 3, {{"sockfd"}, {"addr"}, {"addrlen"}}},
    {"getpeername", 3, {{"sockfd"}, {"addr"}, {"addrlen"}}},
    {"socketpair", 4, {{"domain"}, {"type"}, {"protocol"}, {"sv"}}},
    {"setsockopt",
     5,
     {{"sockfd"}, {"level"}, {"optname"}, {"optval"}, {"optlen"}}},
    {"getsockopt",
     5,
     {{"sockfd"}, {"level"}, {"optname"}, {"optval"}, {"optlen"}}},
    {"clone", 5, {{"flags"}, {"child_stack"}, {"ptid"}, {"ctid"}, {"tls"}}},
    {"fork", 0, {{"null"}}},
    {"vfork", 0, {{"null"}}},
    {"execve", 3, {{"pathname"}, {"argv"}, {"envp"}}},
    {"exit", 1, {{"status"}}},
    {"wait4", 4, {{"pid"}, {"wstatus"}, {"options"}, {"rusage"}}},
    {"kill", 2, {{"pid"}, {"sig"}}},
    {"uname", 1, {{"buf"}}},
    {"semget", 3, {{"key"}, {"nsems"}, {"semflg"}}},
    {"semop", 3, {{"semid"}, {"sops"}, {"nsops"}}},
    {"semctl", 4, {{"semid"}, {"semnum"}, {"cmd"}, {"arg"}}},
    {"shmdt", 1, {{"shmaddr"}}},
    {"msgget", 2, {{"key"}, {"msgflg"}}},
    {"msgsnd", 4, {{"msqid"}, {"msgp"}, {"msgsz"}, {"msgflg"}}},
    {"msgrcv", 5, {{"msqid"}, {"msgp"}, {"msgsz"}, {"msgtyp"}, {"msgflg"}}},
    {"msgctl", 3, {{"msqid"}, {"cmd"}, {"buf"}}},
    {"fcntl", 3, {{"fd"}, {"cmd"}, {"arg"}}},
    {"flock", 2, {{"fd"}, {"operation"}}},
    {"fsync", 1, {{"fd"}}},
    {"fdatasync", 1, {{"fd"}}},
    {"truncate", 2, {{"pathname"}, {"length"}}},
    {"ftruncate", 2, {{"fd"}, {"length"}}},
    {"getdents", 3, {{"fd"}, {"dirp"}, {"count"}}},
    {"getcwd", 2, {{"buf"}, {"size"}}},
    {"chdir", 1, {{"path"}}},
    {"fchdir", 1, {{"fd"}}},
    {"rename", 2, {{"oldpath"}, {"newpath"}}},
    {"mkdir", 2, {{"pathname"}, {"mode"}}},
    {"rmdir", 1, {{"pathname"}}},
    {"creat", 2, {{"pathname"}, {"mode"}}},
    {"link", 2, {{"oldpath"}, {"newpath"}}},
    {"unlink", 1, {{"pathname"}}},
};

char *get_syscall_name(long syscall_number);

#endif /* !MY_STRACE_H */
